### ISSUE TITLE
Roadmap Sénégal

### ISSUE THREAD

**Issue by Leocza** [openfisca/openfisca-senegal#34]
# 1. Identifier les recettes fiscales et dépenses publiques importantes + les autres données de calage utiles

- [ ] Partager les documents officiels/sources (dropbox, drive, ou repos git (mieux non ?))

## 1.1 Postes budgétaires et recettes fiscales

Faire une feuille récapitulative (format csv, séparateur = virgule, sans accent) comportant : 
 
- [ ] le total des **recettes fiscales** générées par impôt (utile aussi pour le **calage**)
- [ ] la **part des recettes** de chaque impôt dans les recettes totales
- [ ] un indicateur allant de 0 à 4 pour déterminer si les données disponibles permettent de calculer l'impôt correctement (0 = pas d'info; 4 = toutes les infos dispo)
- [ ] les **budgets** totaux consacrés à chaque **allocation**
- [ ] le **nombre d'individus** bénéficiant de ces allocations selon les sources différentes de l'enquête
- [ ] les **budgets** consacrés à la **santé** et à **l'éducation** (suivant la méthode de désagrégation choisie) 
- [ ] le nombre d'individus bénéficiant de ces budgets selon les sources différentes de l'enquête
- [ ] l'année de référence
- [ ] la **source**

## 1.2 Autres données de calage : 

Faire une feuille récapitulative (format csv, séparateur = virgule, sans accent) avec : 

- [ ] des données administratives/recensement sur la population (par région, nationalité etc ...) 
- [ ] des données administratives sur la production (par secteur, régions etc ...)
- [ ] des données sur les prix
- [ ] l'année de référence
- [ ] leur **source**

# 2. Explorer la législation et remplir le wiki

Liste est modifiable. Ne remplir le wiki que pour les éléments de fiscalité pertinents, i.e dont les apports budgétaires sont importants. Toujours citer ou référencer les parties pertinentes du code des impôts. (dans le cas de Cote d'Ivoire, pas de PDF dispo et le code change, il est parfois difficile de garder une trace des changements, du coup dans ce cas mieux vaut citer)

## 2.1 Impôts directs

- [ ]  Impôt sur les Traitement et Salaires
- [ ] Impôt sur les Bénéfices Industriels et Commerciaux des entreprises unipersonnelles
- [ ] Contribution Global Unique
- [ ] Taxe Minimum Forfaitaire 
- [ ] Autres ? 

## 2.2 Impôts indirects

- [ ] Taxe sur la valeur ajoutée 
- [ ] Taxes douanières
- [ ] Autres ? 

## 2.3 Allocation et subventions

- [ ] subvention
- [ ] pension ou rente viagère
- [ ] allocation sociale 
- [ ] allocation chômage 

# 3 Faire le lien entre les données micro et la législation

Faire un tableau de toutes les variables tirées de l'enquête (format csv, séparateur = virgule, sans accent) comportant : 
 
- [ ] une colonne rappelant les références de l'enquête (date, nom, source des données)
- [ ] une colonne précisant le nom de la variable
- [ ] une colonne précisant l'unité statistique de la variable 
- [ ] une colonne précisant l'usage que l'on va faire de cette variable : soit caractéristique socio-démographique, soit le nom le l'impôt qu'elle va servir à calculer, soit conso/revenu. 
- [ ] une colonne précisant les références des questions brutes à partir desquelles la variable a été calculée.
- [ ] un commentaire sur la méthode de calcul si pertinent
- [ ] un commentaire sur la qualité de la variable si pertinent (peut-être un indicateur ?)

# 4. Impôt sur les Traitement et Salaires

### 4.1 Revenu imposable 

- [ ] définir les variables qui entrent dans le calcul du revenu imposable
- [ ] définir variables/paramètres nécessaires aux abattements
- [ ] définir les variables/paramètres nécessaires à la prise en compte des cas d'exonérations (si applicable)

## 4.2 Traiter les impôts en plus sur les salaires et à charge de l'employé

- [ ] coder la Taxe Minimum Forfaitare
- [ ] et ajouter les tests

## 4.3 Calcule

- [x] définir le barème
- [x] coder les réductions familiales
- [ ] et ajouter les tests
- [x] coder la méthode de calcul 
- [ ] et ajouter les tests

## 4.4 Cotisations payées par l'employeur

- [ ] pour la sécurité sociale ?
- [ ] pour les retraites ?

# 5. Impôts sur les Bénéfices Industriels et Commerciaux (BIC)

## 5.1 revenu imposable 

- [ ] définir les variables qui entrent dans le calcul du revenu imposable
- [ ] définir variables/paramètres nécessaires aux abattements
- [ ]  définir les variables/paramètres nécessaires à la prise en compte des cas d'exonérations (si applicable)

## 5.2 calcul 

- [ ] définir le barème 
- [ ]  coder la méthode de calcul
- [ ] avec les tests

# 6 taxe sur la valeur ajoutée (TVA) 

# 7 taxe douanières 

## 7.2 A l'importation produits pétroliers

# 8. Autres impôts

**Comment by Leocza** [comment]
@Mouksit @asrobi @nirirazaka j'ai terminé de remplir mes exemples de feuilles csv. Vous trouverez le lien dans ce roadmap. Le lien est temporaire car il redirige vers une branche qui va très vite être mergée. On mettre un truc vers master quand les dossiers assets de tous les repos auront été mergés dans master

**Comment by Mouksit** [comment]
Merci @Leocza
